### ISSUE TITLE
Bot is creating issues and PRs unecessarily

### ISSUE THREAD

**Issue by kennykerr** [microsoft/.github#81]
The windows-rs repo has a security.md in [the .github folder](https://github.com/microsoft/windows-rs/tree/master/.github), but the bot is not finding it.

https://github.com/microsoft/windows-rs/pull/1768
https://github.com/microsoft/windows-rs/issues/1769

**Comment by jeffwilcox** [comment]
@DragosDanielBoia @fossygirl  the URLs were improved previously to match that GitHub doc that Rafael provided a link to, right?

**Comment by DragosDanielBoia** [comment]
@jeffwilcox we are now looking into multiple location, this issue has to be fixed by now.

**Comment by DragosDanielBoia** [comment]
this has been resolved
